-- =============================================================
-- FILE: queries/aggregations.sql
-- PROJECT: Retail Sales Database
-- DESCRIPTION: Aggregation queries using GROUP BY, COUNT, SUM,
--              AVG, and HAVING. Also includes subquery examples.
-- =============================================================


-- -------------------------------------------------------------
-- 1. Total revenue across all delivered orders
-- -------------------------------------------------------------
SELECT
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS total_revenue
FROM order_items oi
INNER JOIN orders o ON oi.order_id = o.order_id
WHERE o.status = 'delivered';


-- -------------------------------------------------------------
-- 2. Total number of orders per status
-- -------------------------------------------------------------
SELECT
    status,
    COUNT(*) AS order_count
FROM orders
GROUP BY status
ORDER BY order_count DESC;


-- -------------------------------------------------------------
-- 3. Revenue generated by each product category
-- -------------------------------------------------------------
SELECT
    cat.category_name,
    COUNT(DISTINCT o.order_id)                      AS total_orders,
    SUM(oi.quantity)                                AS units_sold,
    ROUND(SUM(oi.quantity * oi.unit_price), 2)      AS total_revenue
FROM order_items oi
INNER JOIN products   p   ON oi.product_id  = p.product_id
INNER JOIN categories cat ON p.category_id  = cat.category_id
INNER JOIN orders     o   ON oi.order_id    = o.order_id
GROUP BY cat.category_name
ORDER BY total_revenue DESC;


-- -------------------------------------------------------------
-- 4. Top 5 best-selling products by revenue
-- -------------------------------------------------------------
SELECT
    p.product_name,
    SUM(oi.quantity)                            AS units_sold,
    ROUND(SUM(oi.quantity * oi.unit_price), 2)  AS total_revenue
FROM order_items oi
INNER JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_revenue DESC
LIMIT 5;


-- -------------------------------------------------------------
-- 5. Top 5 customers by total spending
-- -------------------------------------------------------------
SELECT
    c.first_name || ' ' || c.last_name         AS customer_name,
    COUNT(DISTINCT o.order_id)                  AS total_orders,
    ROUND(SUM(oi.quantity * oi.unit_price), 2)  AS total_spent
FROM customers c
INNER JOIN orders      o  ON c.customer_id  = o.customer_id
INNER JOIN order_items oi ON o.order_id     = oi.order_id
GROUP BY c.customer_id, customer_name
ORDER BY total_spent DESC
LIMIT 5;


-- -------------------------------------------------------------
-- 6. Employee performance: number of orders processed per employee
-- -------------------------------------------------------------
SELECT
    e.first_name || ' ' || e.last_name         AS employee_name,
    e.job_title,
    COUNT(o.order_id)                           AS orders_processed,
    ROUND(SUM(oi.quantity * oi.unit_price), 2)  AS revenue_processed
FROM employees e
INNER JOIN orders      o  ON e.employee_id = o.employee_id
INNER JOIN order_items oi ON o.order_id    = oi.order_id
GROUP BY e.employee_id, employee_name, e.job_title
ORDER BY orders_processed DESC;


-- -------------------------------------------------------------
-- 7. Average order value per month
-- -------------------------------------------------------------
SELECT
    STRFTIME('%Y-%m', o.order_date)                                    AS month,
    COUNT(DISTINCT o.order_id)                                         AS total_orders,
    ROUND(SUM(oi.quantity * oi.unit_price), 2)                         AS monthly_revenue,
    ROUND(SUM(oi.quantity * oi.unit_price) / COUNT(DISTINCT o.order_id), 2) AS avg_order_value
FROM orders o
INNER JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY month
ORDER BY month;


-- -------------------------------------------------------------
-- 8. Products with low stock (fewer than 50 units remaining)
-- -------------------------------------------------------------
SELECT
    p.product_name,
    cat.category_name,
    p.stock_qty
FROM products p
INNER JOIN categories cat ON p.category_id = cat.category_id
WHERE p.stock_qty < 50
ORDER BY p.stock_qty;


-- -------------------------------------------------------------
-- 9. Categories with more than 1 product generating over $50 in revenue
--    (HAVING clause — filter on aggregated values)
-- -------------------------------------------------------------
SELECT
    cat.category_name,
    COUNT(DISTINCT p.product_id)                AS product_count,
    ROUND(SUM(oi.quantity * oi.unit_price), 2)  AS total_revenue
FROM order_items oi
INNER JOIN products   p   ON oi.product_id = p.product_id
INNER JOIN categories cat ON p.category_id = cat.category_id
GROUP BY cat.category_name
HAVING total_revenue > 50
   AND product_count > 1
ORDER BY total_revenue DESC;


-- -------------------------------------------------------------
-- 10. Customers who have spent more than the average customer spend
--     (Subquery in WHERE clause)
-- -------------------------------------------------------------
SELECT
    c.first_name || ' ' || c.last_name         AS customer_name,
    ROUND(SUM(oi.quantity * oi.unit_price), 2)  AS total_spent
FROM customers c
INNER JOIN orders      o  ON c.customer_id = o.customer_id
INNER JOIN order_items oi ON o.order_id    = oi.order_id
GROUP BY c.customer_id, customer_name
HAVING total_spent > (
    -- Subquery: calculate the average spend across all customers
    SELECT AVG(customer_total)
    FROM (
        SELECT SUM(oi2.quantity * oi2.unit_price) AS customer_total
        FROM orders o2
        INNER JOIN order_items oi2 ON o2.order_id = oi2.order_id
        GROUP BY o2.customer_id
    )
)
ORDER BY total_spent DESC;
